# https://wiki.hyprland.org/Configuring/Window-Rules/

# layer rules
layerrule = blur,launcher
layerrule = ignorealpha 0, launcher
layerrule = dimaround, launcher
layerrule = animation popin, launcher
layerrule = blur, notifications
layerrule = ignorealpha 0, notifications
#layerrule = animation slide, notifications
layerrule = noanim, notifications # animations on notifications are bugged
layerrule = blur, waybar
layerrule = ignorealpha 0, waybar
layerrule = blurpopups, waybar

# all windows
windowrule=suppressevent maximize, class:.* # You'll probably like this.
windowrule=nofocus, class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0 # fix some dragging issues with XWayland
windowrule=idleinhibit fullscreen, fullscreen:1 # prevent screenlocking if there's a fullscreen window
windowrule=dimaround, floating:1 # force focus on a last opened floating window and dim the screen around it

# ProtonUp-Qt -flatpak
windowrule=float, class:(net.davidotek.pupgui2)$
windowrule=size 600 600, class:(net.davidotek.pupgui2)$
windowrule=center, class:(net.davidotek.pupgui2)$

# blueman
windowrule=float, class:(blueman-manager)$
windowrule=size 800 800, class:(blueman-manager)$
windowrule=center, class:(blueman-manager)$

# nnn preview-tui plugin
windowrule=nofocus, title:(nnnpreviewwindow)$ 
windowrule=nodim, title:(nnnpreviewwindow)$ 
windowrule=group deny, title:(nnnpreviewwindow)$
windowrule=opaque, title:(nnnpreviewwindow)$

# xdg-desktop-portal-gtk
windowrule=float, class:(xdg-desktop-portal-gtk)$
windowrule=size 800 600, class:(xdg-desktop-portal-gtk)$

# pcmanfm-qt - removable media pop-up
windowrule=float, title:(Removable medium is inserted)$
windowrule=size 800 600, title:(Removable medium is inserted)$

# htop
windowrule=float, title:(htop)$
windowrule=size 1400 800, title:(htop)$
windowrule=center, title:(htop)$

# fzmp
windowrule=float, title:(fzmp)$
windowrule=size 1400 800, title:(fzmp)$
windowrule=center, title:(fzmp)$

# nm-connection-editor
windowrule=float, class:(nm-connection-editor)$
windowrule=size 800 600, class:(nm-connection-editor)$
windowrule=center, class:(nm-connection-editor)$

# cliphist-fzf-sixel script
windowrule=float, title:(cliphist)$
windowrule=size 1400 800, title:(cliphist)$
windowrule=center, title:(cliphist)$

# setbg script
windowrule=float, title:(setbg)$
windowrule=size 1400 800, title:(setbg)$
windowrule=center, title:(setbg)$

# com.saivert.pwvucontrol (flatpak)
windowrule=float, class:(com.saivert.pwvucontrol)$
windowrule=size 1400 800, class:(com.saivert.pwvucontrol)$
windowrule=center, class:(com.saivert.pwvucontrol)$

# networkmanager-dmenu - nmcli password terminal window
windowrule=float, title:(nmcli-password)$
windowrule=size 600 600, title:(nmcli-password)$
windowrule=center, title:(nmcli-password)$
