#autostart and flatpaks
$clipboard = uwsm app  -- wl-paste --watch cliphist store
$openfreebuds = flatpak run pw.mmk.OpenFreebuds 
$telegram = flatpak run org.telegram.desktop
$easyeffects = flatpak run com.github.wwmm.easyeffects --gapplication-service
$automount = uwsm app -- udiskie -s

#default apps
$filemanager = $TERMINAL -T nnn  $HOME/.local/bin/nwrap
$menu = fuzzel
$dmenu = fuzzel --dmenu
$clock = $TERMINAL -T tty-clock tty-clock -C3 -c -s -n -f "%A %d %B %Y (%Z)"
$editor = $TERMINAL -T neovim  $EDITOR
$sysmonitor = $TERMINAL -T htop  htop
$hyprsunset = uwsm app -- $HOME/.local/bin/nightlight
$fzmp = $TERMINAL -T fzmp $HOME/.local/bin/fzmp
$logout = uwsm app -- $HOME/.local/bin/powermenu
$network = uwsm app -- networkmanager_dmenu
$colorpicker = uwsm app -- hyprpicker -ar 
$clipboard-copy = cliphist list | $dmenu --width 100 -p '󱃔 clipboard >' | cliphist decode | wl-copy
$screenshot = grim
$screenshot2 = grim -g "$(slurp)"

#actions
$notification-action = makoctl menu $dmenu -p ' action >'
$notification-dismiss = makoctl dismiss --all
$xkb-notify = $HOME/.local/bin/lang
$backlight-up = $HOME/.local/bin/backlight --inc
$backlight-down = $HOME/.local/bin/backlight --dec
$volume-up = $HOME/.local/bin/wpctl-volume --inc
$volume-down = $HOME/.local/bin/wpctl-volume --dec
$volume-toggle = $HOME/.local/bin/wpctl-volume --toggle
