# mod keys
$mainMod = SUPER
$extraMod = SUPER_SHIFT

# local executables path
$BIN = $HOME/.local/bin/

# apps
$openfreebuds = flatpak run pw.mmk.OpenFreebuds 
$telegram = flatpak run org.telegram.desktop
$easyeffects = flatpak run com.github.wwmm.easyeffects --gapplication-service
$filemanager = pcmanfm-qt  # no uwsm app here, because pcmanfm-qt --daemon-mode systemd service runs on the background
$network = uwsm app -- networkmanager_dmenu
$menu = fuzzel
$dmenu = fuzzel --dmenu
$clock = $TERMINAL -T tty-clock tty-clock -C3 -c -s -n -f "%A %d %B %Y (%Z)"
$editor = $TERMINAL -T neovim  $EDITOR
$sysmonitor = $TERMINAL -T htop  htop
$colorpicker = uwsm app -- hyprpicker -ar 
$screenshot = grim
$screenshot2 = grim -g "$(slurp)"

# mako actions
$notification-action = makoctl menu $dmenu -p ' action ❯ '
$notification-dismiss = makoctl dismiss --all

# local scripts
$clipboard = $TERMINAL -T cliphist $BIN/cliphist-fzf-sixel # requires cliphist.service to be enabled and active
$filemanager-tui = $TERMINAL $BIN/nnn-wrapper
$hyprsunset = uwsm app -- $BIN/nightlight
$fzmp = $TERMINAL -T fzmp $BIN/fzmp
$logout = uwsm app -- $BIN/powermenu
$xkb-notify = $BIN/lang
$backlight-up = $BIN/backlight --inc
$backlight-down = $BIN/backlight --dec
$volume-up = $BIN/wpctl-volume --inc
$volume-down = $BIN/wpctl-volume --dec
$volume-toggle = $BIN/wpctl-volume --toggle
