# cursor
cursor {
    no_hardware_cursors = 2
    inactive_timeout = 5
}

# window layouts
dwindle {
    # See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
    pseudotile = true # master switch for pseudotiling.
    preserve_split = true # you probably want this
}

master {
    # See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
    new_status = inherit
}

# misc
binds {
    workspace_back_and_forth = true
    allow_workspace_cycles = true
    movefocus_cycles_groupfirst = true
}

misc {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
    force_default_wallpaper = -1 # Set to 0 or 1 to disable the anime mascot wallpapers
    font_family = FiraCode Nerd Font Mono
    mouse_move_enables_dpms = true
}
