$darkblood = rgb(1a0000)
$darkbloodAlpha = 1a0000

$bloodmoon = rgb(edb7c0) 
$bloodmoonAlpha = edb7c0

$crimson = rgb(9b1120)
$crimsonAlpha = 9b1120

$scarlet = rgb(f38ba8)
$scarletAlpha = f38ba8

$bloodstone = rgb(5b0d1a)
$bloodstoneAlpha = 5b0d1a

$ember = rgb(fa9970)
$emberAlpha = fa9970

$witchfire = rgb(edd85c)
$witchfireAlpha = edd85c

$poison = rgb(2f6030)
$poisonAlpha = 2f6030

$shadowveil = rgb(395e62)
$shadowveilAlpha = 395e62

$ghostlight = rgb(477d89)
$ghostlightAlpha = 477d89

$midnight = rgb(273c5c) 
$midnightAlpha = 273c5c

$witchinghour = rgb(2c3e50) 
$witchinghourAlpha = 2c3e50

$bloodmoonlight = rgb(858ba0)
$bloodmoonlightAlpha = 858ba0

$phantommist = rgb(adb8cf)
$phantommistAlpha = adb8cf

$darkwhisper = rgb(8d93ad)
$darkwhisperAlpha = 8d93ad

$ashenveil = rgb(7980a0)
$ashenveilAlpha = 7980a0

$nightshade = rgb(4f556e)
$nightshadeAlpha = 4f556e

$hauntingdepth = rgb(33384a)
$hauntingdepthAlpha = 33384a

$crypt = rgb(1c1d2e)
$cryptAlpha = 1c1d2e

$eternaldusk = rgb(12121e)
$eternalduskAlpha = 12121e

$darkabyss = rgb(0e1017)
$darkabyssAlpha = 0e1017
