[dmenu]
 dmenu_command = fuzzel --dmenu --width 80 --lines 18 
 active_chars = 
 compact = False
# pinentry = pinentry-qt
 wifi_chars = ▂▄▆█
 wifi_icons = 󰤯󰤟󰤢󰤥󰤨
 format = {icon} {name} {signal} {bars} {sec}  
# list_saved = <True or False> # (Default: False) list saved connections

[dmenu_passphrase]
 obscure = True

[pinentry]
# description = <Pinentry description> (Default: Get network password)
# prompt = <Pinentry prompt> (Default: Password:)

[editor]
 terminal = footclient
# gui_if_available = False
# gui = <name of gui editor> (Default: nm-connection-editor)

[nmdm]
# rescan_delay = <seconds>  # (seconds to wait after a wifi rescan before redisplaying the results)
