# by simla33 https://github.com/InioX/matugen-themes/pull/24
# modified by izmyname

# : Manager [[[

[mgr]
cwd = { fg = "{{colors.on_surface.default.hex}}" }

# Hovered
hovered         = { reversed = true }
preview_hovered = { underline = true }

# Find
find_keyword = { fg = "{{colors.error.default.hex}}", bold = true, italic = true, underline = true }
find_position = { fg = "{{colors.error.default.hex}}", bold = true, italic = true }

# Marker
marker_copied = { fg = "{{colors.tertiary_fixed.default.hex | auto_lightness: 20.0}}", bg = "{{colors.tertiary_fixed.default.hex | auto_lightness: 20.0}}" }
marker_cut = { fg = "{{colors.tertiary_fixed.default.hex}}", bg = "{{colors.tertiary_fixed.default.hex}}" }
marker_marked = { fg = "{{colors.error.default.hex}}", bg = "{{colors.error.default.hex}}" }
marker_selected = { fg = "{{colors.tertiary.default.hex}}", bg = "{{colors.tertiary.default.hex}}" }

# Count
count_copied = { fg = "{{colors.on_tertiary_fixed.default.hex}}", bg = "{{colors.tertiary_fixed.default.hex}}" }
count_cut = { fg = "{{colors.on_tertiary_fixed.default.hex}}", bg = "{{colors.tertiary_fixed.default.hex}}" }
count_selected = { fg = "{{colors.on_primary.default.hex}}", bg = "{{colors.tertiary.default.hex}}" }

# Border
border_symbol = "│"
border_style  = { fg = "{{colors.surface_tint.default.hex}}" }

# : ]]]


# : Tabs [[[

[tabs]
active = { fg = "{{colors.on_primary.default.hex}}", bg = "{{colors.primary.default.hex}}", bold = true }
inactive = { fg = "{{colors.primary_fixed.default.hex}}", bg = "{{colors.on_primary_fixed.default.hex}}"}

# ]]]


# : Mode [[[


[mode]
# Mode
normal_main = { bg = "{{colors.primary.default.hex}}", fg = "{{colors.on_primary.default.hex}}", bold = true }
normal_alt  = { bg = "{{colors.surface_variant.default.hex}}", fg = "{{colors.on_surface_variant.default.hex}}" }

# Select mode
select_main = { bg = "{{colors.secondary.default.hex}}", fg = "{{colors.on_secondary.default.hex}}", bold = true }
select_alt  = { bg = "{{colors.surface_variant.default.hex}}", fg = "{{colors.on_surface_variant.default.hex}}" }

# Unset mode
unset_main = { bg = "{{colors.tertiary.default.hex}}", fg = "{{colors.on_tertiary.default.hex}}", bold = true }
unset_alt  = { bg = "{{colors.surface_variant.default.hex}}", fg = "{{colors.on_surface_variant.default.hex}}" }

# : ]]]


# : Status bar [[[

[status]
# Progress
progress_label = { bold = true }
progress_normal = { fg = "{{colors.primary.default.hex}}", bg = "{{colors.surface_bright.default.hex}}" }
progress_error = { fg = "{{colors.error.default.hex}}", bg = "{{colors.surface_bright.default.hex}}" }

# Permissions
perm_type = { fg = "{{colors.secondary.default.hex | auto_lightness: 30.0}}" }
perm_write = { fg = "{{colors.tertiary.default.hex | auto_lightness: 30.0}}" }
perm_exec = { fg = "{{colors.error.default.hex | auto_lightness: 30.0}}" }
perm_read = { fg = "{{colors.tertiary_fixed.default.hex | auto_lightness: 30.0}}" }
perm_sep = { fg = "{{colors.primary_fixed.default.hex | auto_lightness: 30.0}}" }

# : ]]]


# : Pick [[[

[pick]
border = { fg = "{{colors.primary.default.hex}}" }
active = { fg = "{{colors.tertiary.default.hex}}", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "{{colors.primary.default.hex}}" }
title    = {}
value    = {}
selected = { reversed = true }

# : ]]]


# : Completion [[[

[cmp]
border = { fg = "{{colors.primary.default.hex}}", bg = "{{colors.on_primary.default.hex}}" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "{{colors.primary.default.hex}}" }
title = {}
hovered = { fg = "{{colors.tertiary_fixed.default.hex}}", bold = true }

# : ]]]


# : Which [[[

[which]
mask = { bg = "{{colors.surface_bright.default.hex}}" }
cand = { fg = "{{colors.primary.default.hex}}" }
rest = { fg = "{{colors.on_primary.default.hex}}" }
desc = { fg = "{{colors.on_surface.default.hex}}" }
separator = " ▶ "
separator_style = { fg = "{{colors.on_surface.default.hex}}" }

# : ]]]


# : Help [[[

[help]
on = { fg = "{{colors.on_surface.default.hex}}" }
run = { fg = "{{colors.on_surface.default.hex}}" }
hovered = { reversed = true, bold = true }
footer = { fg = "{{colors.on_secondary.default.hex}}", bg = "{{colors.secondary.default.hex}}" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "{{colors.tertiary.default.hex}}" }
title_warn = { fg = "{{colors.primary.default.hex}}" }
title_error = { fg = "{{colors.error.default.hex}}" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "{{colors.tertiary.default.hex}}" },

    # Media
    { mime = "{audio,video}/*", fg = "{{colors.primary_fixed.default.hex}}" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "{{colors.on_tertiary_container.default.hex}}" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "{{colors.primary_fixed_dim.default.hex}}" },

    # Special files
    { name = "*", is = "orphan", bg = "{{colors.error_container.default.hex}}" },
    { name = "*", is = "exec", fg = "{{colors.on_error_container.default.hex}}" },

    # Fallback
    { name = "*", fg = "{{colors.on_surface.default.hex}}" },
    { name = "*/", fg = "{{colors.surface_tint.default.hex}}" },
]

# : ]]]
